title: "Private Services"
subtitle: "Tailscale-only dashboard"
logo: "assets/logo.png"  # Optional, add your own logo

services:
  - name: "Infrastructure"
    icon: "fas fa-server"
    items:
      - name: "Portainer"
        icon: "fas fa-server"
        url: "http://um.tail16ca22.ts.net:9000"
        description: "Docker management UI"
      - name: "Pi-hole"
        icon: "fas fa-shield-alt"
        url: "http://um.tail16ca22.ts.net:8085"
        description: "Network-wide ad blocking"
      - name: "Vault"
        icon: "fas fa-key"
        url: "http://um.tail16ca22.ts.net:8200"
        description: "Secrets management"
      - name: "Rancher"
        icon: "fas fa-cow"
        url: "https://um.tail16ca22.ts.net:30443"
        description: "Kubernetes management"
# Add more services as needed
