# Custom Traefik values for K3s to avoid conflicts with Docker Compose Traefik
deployment:
  podAnnotations:
    prometheus.io/port: "8082"
    prometheus.io/scrape: "true"

# Use different ports to avoid conflicts with Docker Compose Traefik
entryPoints:
  web:
    address: ":8880"  # K3s HTTP (instead of 80)
  websecure:
    address: ":8888"  # K3s HTTPS (instead of 443)
  traefik:
    address: ":9000"  # K3s Dashboard (instead of 8080)

# Service configuration for external access
service:
  type: LoadBalancer
  spec:
    ports:
    - name: web
      port: 8880
      targetPort: 8880
      protocol: TCP
    - name: websecure
      port: 8888
      targetPort: 8888
      protocol: TCP
    - name: traefik
      port: 9000
      targetPort: 9000
      protocol: TCP
  ipFamilyPolicy: "PreferDualStack"

providers:
  kubernetesIngress:
    publishedService:
      enabled: true

priorityClassName: "system-cluster-critical"

image:
  repository: "rancher/mirrored-library-traefik"
  tag: "3.3.6"

tolerations:
- key: "CriticalAddonsOnly"
  operator: "Exists"
- key: "node-role.kubernetes.io/control-plane"
  operator: "Exists"
  effect: "NoSchedule"
- key: "node-role.kubernetes.io/master"
  operator: "Exists"
  effect: "NoSchedule"

# Enable dashboard
api:
  dashboard: true
  insecure: true

# Add some security headers and configuration
globalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"

# Enable access logs for debugging
logs:
  general:
    level: INFO
  access:
    enabled: true
