apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: default
  labels:
    app: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 100m
            memory: 64Mi
      volumes:
      - name: html-content
        configMap:
          name: hello-world-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-content
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello World - K3s App</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            body { 
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                margin: 0;
                padding: 20px;
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
            }
            .container { 
                background: white;
                max-width: 600px;
                margin: 0 auto;
                padding: 40px;
                border-radius: 10px;
                box-shadow: 0 10px 30px rgba(0,0,0,0.2);
                text-align: center;
            }
            .badge { 
                background: #007acc;
                color: white;
                padding: 8px 16px;
                border-radius: 20px;
                display: inline-block;
                margin: 10px 0;
                font-size: 14px;
            }
            .methods {
                text-align: left;
                background: #f8f9fa;
                padding: 20px;
                border-radius: 8px;
                margin: 20px 0;
            }
            .methods ul {
                list-style: none;
                padding: 0;
            }
            .methods li {
                background: white;
                margin: 8px 0;
                padding: 12px;
                border-radius: 4px;
                border-left: 4px solid #007acc;
            }
            .code {
                font-family: 'Monaco', 'Menlo', monospace;
                background: #f8f9fa;
                padding: 2px 6px;
                border-radius: 3px;
                font-size: 13px;
            }
            h1 { color: #333; margin-bottom: 10px; }
            .timestamp { font-size: 12px; color: #666; margin-top: 20px; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 Hello World from K3s!</h1>
            <div class="badge">Running on Kubernetes</div>
            
            <div class="methods">
                <h3>🌐 Access Methods:</h3>
                <ul>
                    <li><strong>Local (Path-based):</strong><br>
                        <span class="code">https://192.168.1.49:8888/hello</span></li>
                    <li><strong>Local (Host-based):</strong><br>
                        <span class="code">https://hello.nicstack.dev:8888/</span></li>
                    <li><strong>Tailscale:</strong><br>
                        <span class="code">https://your-tailscale-domain.ts.net/hello</span></li>
                    <li><strong>Public Domain:</strong><br>
                        <span class="code">https://hello.nicstack.dev</span></li>
                </ul>
            </div>
            
            <p><strong>Pod Hostname:</strong> <span id="hostname">Loading...</span></p>
            <p><strong>Request Headers:</strong></p>
            <div id="headers" style="font-size: 12px; background: #f8f9fa; padding: 10px; border-radius: 4px; text-align: left;">
                Loading...
            </div>
            
            <div class="timestamp">
                Deployed: <span id="timestamp"></span>
            </div>
        </div>
        
        <script>
            // Show current timestamp
            document.getElementById('timestamp').textContent = new Date().toLocaleString();
            
            // Try to get hostname from environment (this would work with proper setup)
            document.getElementById('hostname').textContent = window.location.hostname || 'hello-world-pod';
            
            // Show some request info
            const headers = {
                'User-Agent': navigator.userAgent.substring(0, 50) + '...',
                'Host': window.location.host,
                'Protocol': window.location.protocol,
                'Path': window.location.pathname
            };
            
            let headerText = '';
            for (let [key, value] of Object.entries(headers)) {
                headerText += key + ': ' + value + '\n';
            }
            document.getElementById('headers').textContent = headerText;
        </script>
    </body>
    </html>
